apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
    - name: cpu-stress
      image: polinux/stress
      resources:
        limits:
          cpu: "1"  # Limite de CPU
      args:
        - "--cpu"
        - "1"     # Usar 1 núcleo da CPU
        - "--timeout"
        - "600s"  # Rodar por 10 minutos
